### ISSUE TITLE
Tracking: master branch rename

### ISSUE THREAD

**Issue by mcornella** [ohmyzsh/ohmyzsh#10314]
- [ ] Rename in GitHub UI
- [ ] Add local repo branch rename logic in `upgrade.sh`
- [ ] Consider zsh plugin managers logic (the org rename worked without issues, this shouldn't be a problem)
- [ ] Consider forks
