### ISSUE TITLE
[Tracking] Terminal and terminfo related issues

### ISSUE THREAD

**Issue by apjanke** [ohmyzsh/ohmyzsh#4344]
This is a tracking issue that collects the various Oh My Zsh issues and pull requests related to terminal configuration, terminal emulators, terminfo, and key bindings.

It's nice to have a list of all these because many of them are related, and existing issues (including closed ones) are good background for current terminal issues.
## Feature Requests
- [x] #4358 – request: Set Tab and/or Window Names Independently
## Issues
- [x] #4916 – Num Pad can't input
- [x] #4872 – Home and End not working in MobaXterm
- [x] #4784 – Home and End not working in PhpStorm terminal in Mac OS/X
- [x] #4540 – history-substring-search key bindings broken
- [x] #4452 – Lockup after pasting non-ascii characters
- [x] #4434 – Keyboard input disabled after paste
- [x] #4213 – duplicate pwd in Terminal.app window title
- [x] #4157 – safe-paste is unsafe in vi mode
- [x] #4075 – tab completion in OS X 10.10 leaving extra characters
- [x] #3757 – Home/End broken in PuTTY
- [x] #3733 – Home/End broken in CentOS
- [x] #3495 – Home/End broken in CentOS
- [x] #3061 – Home/End broken in Ubuntu
- [x] #2698 – Home/End broken in gnome-terminal
- [x] #2696 – Home/End broken on OS X (Terminal.app grabbing Home/End for itself)
- [x] #3658 – hardcoded escapes in installer "echo"
- [x] #3583 – Multibyte chars in Terminal.app pwd URLs get garbled
- [x] #3435 – vi-mode plugin clobbers key bindings
- [x] #3425 – urxvt portability problem with color escape sequences
- [x] #3350 – Tab autocompletion not working for this user
- [x] #3331 – ZOC incompatibility with xterm title-setting escape sequences
- [x] #2750 – Cursor key bindings broken in `urxvt` on openSUSE
- [x] #2735 – history-substring-search key bindings broken after `terminfo` changeover
- [X] ~~#2654 – Num keypad broken on OS X~~
- [X] ~~#2608 – "cannot bind to an empty key sequence" on OS X~~
- [x] #2416 – "terminalapp plugin is broken and obsolete in mavericks"
- [x] #2314 – Line Wrapping Bug
- [X] ~~#2369 – Change to option-arrow behavior on OS X~~
- [X] ~~#1433 – history-substring-search broken on Ubuntu 12.10~~
### tmux / screen  issues
- [x] #3937 – broken colorscheme in tmux
- [x] #3823 – artifacts in neovim embedded terminal due to forced `$TERM` in `.zshrc`
- [x] #3645 – Emacs terminal emulator issues: artifacts after autocomplete
- [x] #3579 – AUTO_TITLE broken in tmux
### Pull Requests
- [x] #4251 – Fix completion waiting dots line wrapping
- [x] #4193 – history-substring-search: bind arrows in both vi and emacs keymaps (after updating histsubstr from upstream)
- [x] #4192 – history-substring-search: bind arrows in both vi and emacs keymaps 
- [x] #4191 – vi-mode: remove broken line-init/finish widgets
- [x] #3790 – iTerm2 profile control support
- [x] #3761 – vi-mode changes, using terminal control sequences and bindings
- [x] #3727 – selectability of choosing method of setting terminal titles
- [x] #3664 – installer: use printf and terminfo for portability
- [x] #3627 – "Better research history" that changes `lib/key-bindings`
- [x] #3616 – vi-mode: adds more key bindings
- [x] #3582 – Fold terminalapp plugin in to `lib/termsupport`
- [x] #2875 – Remove `screen*` support from `lib/termsupport`
- [x] #2805 – iTerm2 tab colorization
- [x] #2739 – Term window title setting under cygwin prompt
- [x] #2445 – "Fixing iTerm Tmux integration"
- [x] ~~#1907 – `lib/keybindings`: "rebind key for editor"~~
- [x] ~~#1629 – "Special" high-precedence key bindings using terminfo~~
- [x] #1491 – screen: "Bugfix extracted cmd"
#### Important Historical Pull Requests
- [x] #1355 – Change hardcoded escapes to `terminfo` lookups in `lib/keybindings`
## References
- My spreadsheet of observed terminal key behavior:  https://docs.google.com/spreadsheets/d/1Ue5gb2hLjz058QEtEXwaw8YR7QoVZpSYzbXQKrRcGKk/edit?usp=sharing
- [iTerm2 issue 3753](https://gitlab.com/gnachman/iterm2/issues/3753) - character sequences emitted by iTerm2 for Alt-Arrow keystrokes

**Comment by larson-carter** [comment]
@apjanke Can I please get an update on this issue?

**Comment by apjanke** [comment]
Hi @larson-carter! I'm on the road this weekend, but will try to address this when I get back home mid next week.

**Comment by larson-carter** [comment]
@apjanke Thank you!

**Comment by mcornella** [comment]
All work is done or obsolete, so I'm closing this. Thanks a lot for your hard work Andrew!
